services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    user: "1000:100"
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    user: "1000:100"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
